### ISSUE TITLE
Tools by Docker

### ISSUE THREAD

**Issue by andreyrikunov** [RoRu/Video-Packager#5]
Complex workflows require many command line tools to be provisioned. They have to be preinstalled or downloaded before workflow proceed. Preinstalled tools are fine for local development environment.  In production environment the commandline tools should be somehow provided at runtime. Tools management and provisioning are good to be inverted of control. This is there where the Docker is very good for. Let's pack all required tools into Docker image and run our workflows with it providing all required tools in Docker way.

As the first step let's dockerize Ubuntu Linux and FFMPEG 4.0.x with libx265 support.

**Comment by dxahtepb** [comment]
The simpliest (and still the best) way to dockerize required tools is just to download a well-composed docker image (like [jrottenberg/ffmpeg:4.0-ubuntu](https://hub.docker.com/r/jrottenberg/ffmpeg/builds/bw4dqxsfqcjczypuixbmuqr/)). This image provides all neccessary tools and it's only 200Mb in size.

Of course, one could build his/her own docker image according to [ffmpeg_compile_guide](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu), if any additional third-party libraries for ffmpeg are needed (or more tools). There is no need in building libraries from sources, as long as ubuntu ppa contains all neccessary versions. Resulting docker image turned out to be too fat (~700Mb), maybe because of statically linked libraries.

Dockerfile and cwl examples are in [PR#6](https://github.com/RoRu/Video-Packager/pull/6)
